# Generated by Django 2.2.24 on 2022-05-26 16:30

from django.db import migrations
import phonenumbers


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220526_1703'),
    ]

    def create_valid_phonenumber(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        flat_phonenumbers = Flat.objects.all()
        for number in flat_phonenumbers:
            number_parse = phonenumbers.parse(number.owners_phonenumber, 'RU')
            if phonenumbers.is_possible_number(number_parse) and phonenumbers.is_valid_number(number_parse):
                number.owner_pure_phone = phonenumbers.format_number(
                    number_parse, phonenumbers.PhoneNumberFormat.INTERNATIONAL
                )
                number.save()

    operations = [
        migrations.RunPython(create_valid_phonenumber),
    ]

