# Generated by Django 2.2.24 on 2022-05-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220526_2127'),
    ]
    def copy_owner_flat(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
        flats = Flat.objects.all()
        for flat in flats:
            owner,created = Owner.objects.get_or_create(
                owner=flat.owner,
                owner_pure_phone=flat.owner_pure_phone,
            )
            owner.owner_flat.add(flat)

    operations = [
        migrations.RunPython(copy_owner_flat),
    ]
