# Generated by Django 2.2.24 on 2022-05-27 09:53

from django.db import migrations


def copy_owner_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        owner, created = Owner.objects.get_or_create(
            owner=flat.owner,
            owner_pure_phone=flat.pure_phonenumber,
        )
        owner.owner_flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220526_2127'),
    ]

    operations = [
        migrations.RunPython(copy_owner_flat),
    ]
